# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:8093/v1/students/add
Content-Type: application/json

{
  "name": "XYI",
  "dob": "2005-07-25"
}

###
//Press Ctrl+Alt+Shift+Insert and select HTTP Request.

DELETE http://localhost:8093/v1/students/delete/405
Content-Type: application/json

###
PUT http://localhost:8093/v1/students/edit
Content-Type: application/json

{
  "id": 404,
  "name": "Tomas1",
  "dob": "2005-07-06"
}

###
POST http://localhost:8093/v1/students/add
Content-Type: application/json

{
  "name": "Mari",
  "email": "alex@gmail.com",
  "dob": "2005-07-25"
}

###
